# Numpy Assignment 2

In [1]:
import numpy as np

### 1. Create a NumPy array containing integers from 0 to 9.

In [2]:
arr1 = np.arange(0,10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 2. Create a NumPy array from a given Python list [10, 20, 30, 40, 50].

In [3]:
arr2 = np.array([10, 20, 30, 40, 50])
arr2

array([10, 20, 30, 40, 50])

### 3. Create a 2D array (3x3) with values ranging from 0 to 8.

In [4]:
arr3 = np.arange(0,9).reshape(3,3)
arr3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 4. Given a 2D array, find its shape and size. Create a 5x4 array with random integers between 1 and 100, and print the shape and size.

In [5]:
arr4 = np.random.randint(1, 100,(5,4))
print(arr4.shape)
print(arr4.size)

(5, 4)
20


### 5. Create a 3x3 array of integers and access:
    a. The second element of the first row.
    b. The third column of the 2nd row.
    c. A subarray with the first two rows and last two columns.

In [6]:
arr5 = np.random.randint(1,100,(3,3))
print(arr5)
print(arr5[0,1])
print(arr5[1,2])
print(arr5[0:2,1:])

[[54 45 56]
 [ 3  4 70]
 [86 64 24]]
45
70
[[45 56]
 [ 4 70]]


### 6. Create a 1D array of 12 elements. Reshape it into a 3x4 2D array.

In [7]:
arr6 = np.arange(1,13)
arr6.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### 7. Reshape a 3x3 matrix into a 1D array.

In [8]:
arr7 = np.random.randint(10,100,(3,3))
print(arr7)
print(arr7.flatten())
print(arr7.ravel())
print(arr7.reshape(-1))

[[85 60 26]
 [88 27 77]
 [65 71 92]]
[85 60 26 88 27 77 65 71 92]
[85 60 26 88 27 77 65 71 92]
[85 60 26 88 27 77 65 71 92]


### 8. Create two arrays of shape (2, 3): arr1 and arr2. Perform element-wise addition, subtraction, multiplication, and division on them.

In [9]:
array1 = np.random.randint(10,100,(2,3))
array2 = np.random.randint(10,100,(2,3))
print(array1)
print(array2)
print("Addition\n",array1 + array2)
print("Subtraction\n",array1 - array2)
print("Multipliication\n",array1 * array2)
print("Division\n",array1 / array2)

[[11 21 80]
 [75 42 38]]
[[17 53 83]
 [33 91 31]]
Addition
 [[ 28  74 163]
 [108 133  69]]
Subtraction
 [[ -6 -32  -3]
 [ 42 -49   7]]
Multipliication
 [[ 187 1113 6640]
 [2475 3822 1178]]
Division
 [[0.64705882 0.39622642 0.96385542]
 [2.27272727 0.46153846 1.22580645]]


### 9. Use NumPy's built-in functions to compute the sum, mean, and standard deviation of a given array.

In [10]:
arr9 = np.arange(10,101,10)
print(arr9)
print(arr9.sum())
print(arr9.mean())
print(arr9.std())

[ 10  20  30  40  50  60  70  80  90 100]
550
55.0
28.722813232690143


### 10. Create a 2x2 matrix A and a 2x2 matrix B. Perform matrix multiplication using np.dot() or the @ operator.

In [11]:
A = np.arange(10,14).reshape(2,2)
B = np.arange(20,24).reshape(2,2)
print(A)
print(B)
print(A @ B)

[[10 11]
 [12 13]]
[[20 21]
 [22 23]]
[[442 463]
 [526 551]]


### 11. Find the transpose of matrix A and matrix B.

In [12]:
print(A.T)
print(B.T)

[[10 12]
 [11 13]]
[[20 22]
 [21 23]]


### 12. Create a 3x3 array and a 1D array with 3 elements. Add the 1D array to the 2D array. Explain how broadcasting works in this operation.

In [13]:
a1 = np.arange(1,10).reshape(3,3)
a2 = np.array([10, 20, 30])
print(a1)
print(a2)
a1 + a2

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[10 20 30]


array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39]])

### 13. Create a 4x4 array of random integers. Find the maximum, minimum, and mean of the entire array.

In [14]:
arr13 = np.random.randint(10,100,(4,4))
print(arr13)
print("Maximum :",np.max(arr13))
print("Minimum :",np.min(arr13))
print("Mean :",np.mean(arr13))

[[39 59 72 26]
 [24 75 78 50]
 [41 79 37 50]
 [80 77 86 48]]
Maximum : 86
Minimum : 24
Mean : 57.5625


### 14. Find the row-wise and column-wise sums.

In [15]:
arr14 = np.arange(10,91,10).reshape(3,3)
print(arr14)
print("Row-Wise Sum :",np.sum(arr14, axis=1))
print("Column-Wise Sum :",np.sum(arr14, axis=0))

[[10 20 30]
 [40 50 60]
 [70 80 90]]
Row-Wise Sum : [ 60 150 240]
Column-Wise Sum : [120 150 180]


### 15. Generate an array of 10 random integers between 1 and 50.

In [19]:
arr15 = np.random.randint(1,51,10)
arr15

array([ 4, 47, 16, 11,  1,  1, 36, 24, 49, 33], dtype=int32)

### 16. Generate a 5x5 matrix of random floats between 0 and 1.

In [26]:
arr16 = np.random.rand(5,5)
arr16

array([[0.2244496 , 0.67849699, 0.01136233, 0.67526436, 0.3101274 ],
       [0.04251669, 0.40975703, 0.28752263, 0.69921456, 0.06583246],
       [0.42975973, 0.80506304, 0.82093804, 0.37381272, 0.83074997],
       [0.84608848, 0.18236925, 0.47882719, 0.3812751 , 0.91340089],
       [0.59168948, 0.72652551, 0.20614895, 0.35897368, 0.61435496]])