# Numpy Assignment 1

In [1]:
import numpy as np

### Q1. Write code to create a 4x3 matrix with values ranging from 2 to 13.

In [2]:
arr1 = np.arange(2,14).reshape(4,3)
arr1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

### Q2. Write code to replace the odd numbers by -1 in the array created by using random.randint( 1 , 50,20)

In [3]:
arr2 = np.random.randint(1,50,20)
arr2

array([ 5, 17, 47, 16,  5, 19,  1, 30,  6, 27, 14, 31, 35,  5, 44, 25, 38,
       40, 19,  1], dtype=int32)

In [4]:
arr2[arr2 % 2 != 0] = -1
arr2

array([-1, -1, -1, 16, -1, -1, -1, 30,  6, -1, 14, -1, -1, -1, 44, -1, 38,
       40, -1, -1], dtype=int32)

### Q3. Perform the following operations on an array of mobile phones prices 6999, 7500, 11999, 27899, 14999, 9999.

#### a. Create a 1d-array of mobile phones prices

In [5]:
mo_price = np.array([6999, 7500, 11999, 27899, 14999, 9999])
mo_price

array([ 6999,  7500, 11999, 27899, 14999,  9999])

#### b. Convert this array to float type

In [6]:
mo_price = mo_price.astype(float)
mo_price

array([ 6999.,  7500., 11999., 27899., 14999.,  9999.])

#### c. Append a new mobile having price of 13999 Rs. to this array

In [7]:
mo_price = np.append(mo_price, 13999)
mo_price

array([ 6999.,  7500., 11999., 27899., 14999.,  9999., 13999.])

#### d. Reverse this array of mobile phones prices

In [8]:
mo_price = mo_price[::-1]
mo_price

array([13999.,  9999., 14999., 27899., 11999.,  7500.,  6999.])

#### e. Apply GST of 18% on mobile phones prices and update this array.

In [9]:
mo_price = mo_price + (mo_price * 18/100)
mo_price

array([16518.82, 11798.82, 17698.82, 32920.82, 14158.82,  8850.  ,
        8258.82])

#### f. Sort the array in descending order of price

In [10]:
mo_price = np.sort(mo_price)[::-1]
mo_price

array([32920.82, 17698.82, 16518.82, 14158.82, 11798.82,  8850.  ,
        8258.82])

#### g. What is the average mobile phone price

In [11]:
np.average(mo_price)

np.float64(15743.560000000001)

#### h. What is the difference b/w maximum and minimum price

In [12]:
np.max(mo_price)  - np.min(mo_price)

np.float64(24662.0)

### Q4. Find out the indices of non zero element in given array [1,2,0,0,4,0]

In [13]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4]),)