In [ ]:
import numpy as np

In [ ]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
matrix[0]

array([1, 2, 3])

In [ ]:
matrix[1]

array([4, 5, 6])

In [ ]:
matrix[:]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
matrix[::-1]

array([[4, 5, 6],
       [1, 2, 3]])

In [ ]:
matrix[1][0]