In [1]:
import numpy as np

#### Method 1

In [2]:
arr1 = np.arange(1,11)
type(arr1)

numpy.ndarray

In [3]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
#### Method 2

In [5]:
arr2 = np.array([1,2,3,4,5,6,7,8,9,10])
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr2[0]

np.int64(1)

In [8]:
import sys
sys.getsizeof(arr1[0])

32

In [9]:
sys.getsizeof(arr2)

192

In [10]:
li1 = [10, 20, 30, 40, 50]

In [11]:
sys.getsizeof(li1)

104

In [12]:
arr1.ndim

1

In [13]:
arr2.ndim

1

In [14]:
arr2.shape

(10,)

In [15]:
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### Multidmensional array

In [17]:
a = np.array(10)

In [18]:
a.ndim

0

In [19]:
arr2d = np.arange(1, 10).reshape((3, 3))
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
arr3d = np.arange(1, 19).reshape((2, 3, 3))
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [23]:
arr_empty = np.empty((3, 3))
arr_empty

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
arr1s = np.ones((3,3))
arr1s

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [27]:
arr0s = np.zeros((3,3))
arr0s

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [28]:
arr_eye = np.eye(3, 3)
arr_eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Functions

In [31]:
arr1 = np.arange(1, 13).reshape(4, 3)
arr1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [32]:
arr1.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [33]:
np.ravel(arr1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [34]:
arr1.flatten('C')

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [36]:
arr1.flatten('F') # Fortran style

array([ 1,  4,  7, 10,  2,  5,  8, 11,  3,  6,  9, 12])

In [38]:
arr1.transpose()

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [39]:
arr1.T

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])