In [1]:
import numpy as np

In [2]:
arr = np.array([10, 3.14, 20, 30, 40])
arr

array([10.  ,  3.14, 20.  , 30.  , 40.  ])

In [10]:
arr = np.array(['abc', 3.14, 101])
arr

array(['abc', '3.14', '101'], dtype='<U32')

## Concatenation and Split

In [3]:
arr1 = np.arange(1, 21).reshape((5, 4))
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [4]:
arr2 = np.arange(21, 41).reshape((5, 4))
arr2

array([[21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32],
       [33, 34, 35, 36],
       [37, 38, 39, 40]])

In [5]:
np.concatenate((arr1, arr2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32],
       [33, 34, 35, 36],
       [37, 38, 39, 40]])

In [9]:
np.concatenate((arr1, arr2),axis=1)

array([[ 1,  2,  3,  4, 21, 22, 23, 24],
       [ 5,  6,  7,  8, 25, 26, 27, 28],
       [ 9, 10, 11, 12, 29, 30, 31, 32],
       [13, 14, 15, 16, 33, 34, 35, 36],
       [17, 18, 19, 20, 37, 38, 39, 40]])

## Spilt

In [12]:
np.split(arr1, 2, axis=1)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16],
        [19, 20]])]