# Numpy

In [1]:
import numpy as np

In [2]:
arr = np.array([10, 20, 30, 40, 50])
arr

array([10, 20, 30, 40, 50])

In [3]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr.shape

(10,)

In [5]:
arr.ndim

1

In [6]:
arr.dtype

dtype('int64')

In [7]:
arr = np.arange(1, 13).reshape(3,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
arr = np.ones((3, 4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
arr = np.zeros((2,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
arr = np.empty((4,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
arr = np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
arr = np.arange(1, 7).reshape(2, 3)
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [14]:
arr = np.linspace(1,10,5)
arr

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [15]:
arr = np.arange(1, 7).reshape(2, 3)
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
arr.flatten('C')

array([1, 2, 3, 4, 5, 6])

In [17]:
arr.flatten('F')

array([1, 4, 2, 5, 3, 6])

In [18]:
arr.ravel()

array([1, 2, 3, 4, 5, 6])

In [19]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

In [20]:
a + b

array([11, 22, 33])

In [21]:
a - b

array([ 9, 18, 27])

In [22]:
a * b

array([10, 40, 90])

In [23]:
a / b

array([10., 10., 10.])

In [24]:
a // b

array([10, 10, 10])

In [25]:
a % b

array([0, 0, 0])

In [26]:
np.add(a, b)

array([11, 22, 33])

In [27]:
np.subtract(a,b)

array([ 9, 18, 27])

In [28]:
np.multiply(a, b)

array([10, 40, 90])

In [29]:
np.divide(a,b)

array([10., 10., 10.])

In [30]:
np.min(arr)

np.int64(1)

In [31]:
arr.min()

np.int64(1)

In [32]:
arr.max()

np.int64(6)

In [33]:
arr.argmin()

np.int64(0)

In [34]:
arr.argmax()

np.int64(5)

In [35]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

In [37]:
A @ B

array([[19, 22],
       [43, 50]])

In [38]:
marks = np.array([10, 20, 30, 40, 50])

In [39]:
marks.mean()

np.float64(30.0)

In [40]:
np.median(marks)

np.float64(30.0)

In [41]:
marks.std()

np.float64(14.142135623730951)

In [42]:
np.sqrt(100)

np.float64(10.0)

In [43]:
np.log(10)

np.float64(2.302585092994046)

In [44]:
np.log10(100)


np.float64(2.0)

#### slicing

In [45]:
arr = np.arange(1,13).reshape(3,4)

In [46]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [47]:
arr[0:2, 0:2]

array([[1, 2],
       [5, 6]])

In [48]:
marks = np.array([1,2,3,4,5,6,7,8,9])
marks.std()

np.float64(2.581988897471611)

#### Concatenate 

In [52]:
a = np.arange(1,13).reshape(4,3)
arr

array([[13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]])

In [53]:
b = np.arange(13,25).reshape(4,3)
b

array([[13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]])

In [55]:
np.concatenate((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]])

In [60]:
np.concatenate((a,b), axis=1)

array([[ 1,  2,  3, 13, 14, 15],
       [ 4,  5,  6, 16, 17, 18],
       [ 7,  8,  9, 19, 20, 21],
       [10, 11, 12, 22, 23, 24]])

#### Split

In [66]:
np.split(a, 3, axis=1)

[array([[ 1],
        [ 4],
        [ 7],
        [10]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12]])]

#### Random

In [67]:
np.random.random()

0.6625825913499842

In [68]:
np.random.rand(2,3)

array([[0.91690831, 0.2067883 , 0.19870746],
       [0.0610439 , 0.82998235, 0.58578295]])

In [74]:
np.random.randn(4,3)

array([[ 1.3315865 ,  0.71527897, -1.54540029],
       [-0.00838385,  0.62133597, -0.72008556],
       [ 0.26551159,  0.10854853,  0.00429143],
       [-0.17460021,  0.43302619,  1.20303737]])

In [73]:
np.random.seed(10)

In [81]:
np.random.randint(1,100, (3,4))

array([[12, 18, 47,  8],
       [76, 29, 34, 85],
       [97, 89, 45,  6]], dtype=int32)