In [1]:
import numpy as np

In [6]:
np.random.randint(35, 95, (20, 6))

array([[86, 91, 88, 94, 36, 38],
       [66, 94, 88, 55, 82, 71],
       [58, 59, 91, 86, 50, 79],
       [72, 89, 92, 52, 50, 92],
       [92, 67, 66, 47, 83, 76],
       [80, 63, 64, 82, 66, 63],
       [70, 90, 88, 63, 56, 41],
       [72, 53, 80, 75, 52, 66],
       [50, 92, 74, 46, 53, 38],
       [46, 58, 37, 54, 79, 41],
       [40, 65, 35, 90, 78, 39],
       [40, 78, 77, 68, 65, 64],
       [77, 71, 57, 94, 35, 93],
       [83, 80, 90, 92, 41, 68],
       [93, 39, 40, 37, 93, 44],
       [84, 39, 76, 54, 51, 57],
       [52, 94, 71, 54, 45, 85],
       [82, 74, 52, 37, 94, 92],
       [80, 75, 92, 86, 54, 64],
       [46, 53, 73, 38, 85, 91]], dtype=int32)

In [8]:
np.random.random() # gives 0 t0 1

0.8026883346409261

In [9]:
np.random.randn(10)

array([ 2.05741235, -0.68861165, -1.03452343, -1.01779729, -0.20580462,
       -0.01935751, -1.42539878,  0.46681965, -0.68130398, -1.939545  ])

In [24]:
np.random.seed(50)
np.random.randint(1, 100, 1)

array([49], dtype=int32)